### ISSUE TITLE
Add `Charset Normalizer 3.2.0` / latest to the page/site

### ISSUE THREAD

**Issue by DeflateAwning** [Ousret/charset_normalizer_web#2]
https://charsetnormalizerweb-ousret.vercel.app currently only has up to Charset Normalizer 3.0.0. Would be great to add a later version than that to it! Maybe there's a way to automatically keep it running on the latest deployed version.

**Comment by Ousret** [comment]
This is now updated. I do not plan for any automation on that part.
it often crashes due to breaking changes in the dependency chain.

we could pin down those, but the platform may at its own discretion upgrade the interpreter and the problem will remain the same eventually (even through a proper github workflow / crontab)

**Comment by DeflateAwning** [comment]
Fair enough, that does sound like it'd be a pain to implement. Good stuff! Thanks!
